# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables

name = "embedded-wallet-verify-session"
pages_build_output_dir = "./dist"
[vars]
    
# Should be equal to the audience claim in the JWT that you want to verify which will be of the form https://sequence.build/project/*projectID*
BUILDER_PROJECT_ID = "13639"

[dev]
port = 4444
